/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_submod.h
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:45:41 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the yaw_model.c file
*/

#ifndef Yaw_SUBMOD_H
#define Yaw_SUBMOD_H

/* Our own include files */
#include "yaw_model.h"

/* Submodel I/O variables */
extern YawInteger yaw_number_of_inputs;
extern YawInteger yaw_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern YawString yaw_input_names[];
extern YawString yaw_output_names[];


/* The submodel functions */
void YawInitializeSubmodel (YawDouble *u, YawDouble *y, YawDouble t);
void YawCalculateSubmodel (YawDouble *u, YawDouble *y, YawDouble t);
void YawTerminateSubmodel (YawDouble *u, YawDouble *y, YawDouble t);
void YawCopyInputsToVariables (YawDouble *u);
void YawCopyVariablesToOutputs (YawDouble *y);

#endif

