/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_submod.c
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:45:41 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "yaw_model.h"
#include "yaw_integ.h"
#include "yaw_funcs.h"
#include "yaw_submod.h"

/* The submodel I/O variables */
YawInteger yaw_number_of_inputs = 2;
YawInteger yaw_number_of_outputs = 2;

/* the names of the submodel io variables
   uncomment this part if you need these names
YawString yaw_input_names[] = {
	"in",
	"position"
,	NULL
};
YawString yaw_output_names[] = {
	"corr",
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void YawCopyInputsToVariables (YawDouble *u)
{
	/* Copy the input vector to the input variables */
	yaw_V[7] = u[0];		/* in */
	yaw_V[8] = u[1];		/* position */

}

/* This function uses the output variables to fill the output vector */
void YawCopyVariablesToOutputs (YawDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	yaw_V[6];		/* corr */
	y[1] = 	yaw_V[9];		/* out */

}

/* The initialization function for submodel */
void YawInitializeSubmodel (YawDouble *u, YawDouble *y, YawDouble t)
{
	/* Initialization phase (allocating memory) */
	yaw_initialize = YawTRUE;
	yaw_steps = 0;
	YawModelInitialize ();
	YawDiscreteInitialize ();

	/* Copy the inputs */
	yaw_time = t;
	YawCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	YawCalculateInitial ();
	YawCalculateStatic ();
	YawCalculateInput ();
	YawCalculateDynamic ();
	YawCalculateOutput ();

	/* Set the outputs */
	YawCopyVariablesToOutputs (y);

	/* End of initialization phase */
	yaw_initialize = YawFALSE;
}

/* The function that calculates the submodel */
void YawCalculateSubmodel (YawDouble *u, YawDouble *y, YawDouble t)
{
	/* Copy the inputs */
	yaw_time = t;
	YawCopyInputsToVariables (u);

	/* Calculate the model */
	YawCalculateInput ();
	YawDiscreteStep ();
	YawCalculateOutput ();

	/* Copy the outputs */
	YawCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void YawTerminateSubmodel (YawDouble *u, YawDouble *y, YawDouble t)
{
	/* Copy the inputs */
	yaw_time = t;
	YawCopyInputsToVariables (u);

	/* Calculate the final model equations */
	YawCalculateFinal ();

	/* Set the outputs */
	YawCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	YawModelTerminate ();
	YawDiscreteTerminate ();
}

