/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_model.h
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:45:41 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the yaw_model.c file
*/

#ifndef Yaw_MODEL_H
#define Yaw_MODEL_H

/* Our own include files */
#include "yaw_types.h"

/* Simulation variables */
extern YawDouble yaw_start_time;
extern YawDouble yaw_finish_time;
extern YawDouble yaw_step_size;
extern YawDouble yaw_time;
extern YawInteger yaw_steps;
extern YawBoolean yaw_initialize;
extern YawBoolean yaw_major;
extern YawBoolean yaw_stop_simulation;

/* Model size constants */
#define yaw_constants_size 0
#define yaw_parameters_size 7
#define yaw_initialvalues_size 3
#define yaw_variables_size 10
#define yaw_states_size 3

/* Variable arrays */
extern YawDouble yaw_P[];
extern YawDouble yaw_I[];
extern YawDouble yaw_V[];
extern YawDouble yaw_s[];
extern YawDouble yaw_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern YawString yaw_parameter_names[];
extern YawString yaw_initial_value_names[];
extern YawString yaw_variable_names[];
extern YawString yaw_state_names[];
extern YawString yaw_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void YawModelInitialize (void);
/* Initialize specific model values */
void YawModelInitialize_parameters(void);
void YawModelInitialize_initialvalues(void);
void YawModelInitialize_states(void);
void YawModelInitialize_variables(void);
void YawModelTerminate (void);

/* Computation methods */
void YawCalculateInitial (void);
void YawCalculateStatic (void);
void YawCalculateInput (void);
void YawCalculateDynamic (void);
void YawCalculateOutput (void);
void YawCalculateFinal (void);


#endif

