/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_funcs.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:45:41 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

#ifndef Yaw_FUNCS_H
#define Yaw_FUNCS_H

/* Our own include files */
#include "yaw_types.h"

/* Global constants */
extern YawBoolean yaw_initialize;
extern YawBoolean yaw_major;
extern YawBoolean yaw_stop_simulation;

/* Wrapper functions around strings */
YawDouble YawString2Double(const char* argument);
const char* YawDouble2String(YawDouble argument);

/* 20-sim function prototypes */
/* 20-sim stub prototypes */
#endif

