/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_main.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:48:36 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file is a demo application of how the submodel function can 
 * be used. It uses the global time variables that are used by both
 * the submodel and the integration method.
 *
 * PLEASE NOTE: THIS IS AN EXAMPLE WHERE ALL INPUTS ARE ZERO ! 
 * USE YOUR OWN INPUTS INSTEAD!! ALSO THE SUBMODEL MIGHT SIMPLY 
 * NOT WORK CORRECTLY WITH INPUTS THAT ARE ZERO.
 */

/* 20-sim include files */
#include "pitch_submod.h"

/* The main function */
int main()
{
	PitchDouble u [3 + 1];
	PitchDouble y [1 + 1];

	/* Initialize the inputs and outputs with correct initial values */
	u[0] = 0.0;		/* corr */
	u[1] = 0.0;		/* in */
	u[2] = 0.0;		/* position */

	y[0] = 0.0;		/* out */


	/* Initialize the submodel itself */
	PitchInitializeSubmodel (u, y, pitch_time);

	/* Simple loop, the time is incremented by the integration method */
	while ( (pitch_time < pitch_finish_time) && (pitch_stop_simulation == PitchFALSE) )
	{
		/* Call the submodel to calculate the output */
		PitchCalculateSubmodel (u, y, pitch_time);
	}

	/* Perform the final calculations */
	PitchTerminateSubmodel (u, y, pitch_time);

	/* and we are done */
	return 0;
}

