/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_model.c
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:48:36 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   PitchDouble pitch_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   PitchString pitch_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void PitchCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>
#include <string.h>

/* 20-sim include files */
#include "pitch_model.h"
#include "pitch_funcs.h"
#include "../jiwy_20sim_tuning.h"

/* the global variables */
PitchDouble pitch_start_time = 0.0;
PitchDouble pitch_finish_time = 20.0;
PitchDouble pitch_step_size = 0.01;
PitchDouble pitch_time = 0.0;
PitchInteger pitch_steps = 0;
PitchBoolean pitch_initialize = PitchTRUE;
PitchBoolean pitch_major = PitchTRUE;
PitchBoolean pitch_stop_simulation = PitchFALSE;

/* the variable arrays */
PitchDouble pitch_P[pitch_parameters_size];		/* parameters */
PitchDouble pitch_I[pitch_initialvalues_size];		/* initial values */
PitchDouble pitch_V[pitch_variables_size];		/* variables */
PitchDouble pitch_s[pitch_states_size];		/* states */
PitchDouble pitch_R[pitch_states_size];		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
PitchString pitch_parameter_names[] = {
	"corrGain\\K",
	"PID1\\kp",
	"PID1\\tauD",
	"PID1\\beta",
	"PID1\\tauI",
	"SignalLimiter2\\minimum",
	"SignalLimiter2\\maximum"
,	NULL
};
PitchString pitch_initial_value_names[] = {
	"PID1\\uD_previous_initial",
	"PID1\\error_previous_initial",
	"PID1\\uI_previous_initial"
,	NULL
};
PitchString pitch_variable_names[] = {
	"corrGain\\input",
	"corrGain\\output",
	"PID1\\output",
	"",
	"PlusMinus1\\output",
	"PlusMinus2\\plus1",
	"PlusMinus2\\minus1",
	"SignalLimiter2\\output",
	"corr",
	"in",
	"position",
	"out"
,	NULL
};
PitchString pitch_state_names[] = {
	"PID1\\uD_previous",
	"PID1\\error_previous",
	"PID1\\uI_previous"
,	NULL
};
PitchString pitch_rate_names[] = {
	"",
	"PID1\\error",
	""
,	NULL
};
*/

#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
void PitchModelInitialize_parameters(void)
{
	/* set the parameters */
	pitch_P[0] = JIWY_PITCH_CORR_GAIN;		/* corrGain\K */
	pitch_P[1] = JIWY_PITCH_KP;		/* PID1\kp */
	pitch_P[2] = JIWY_PITCH_TAU_D;		/* PID1\tauD */
	pitch_P[3] = JIWY_PITCH_BETA;		/* PID1\beta */
	pitch_P[4] = JIWY_PITCH_TAU_I;		/* PID1\tauI */
	pitch_P[5] = JIWY_PITCH_OUTPUT_MIN;		/* SignalLimiter2\minimum */
	pitch_P[6] = JIWY_PITCH_OUTPUT_MAX;		/* SignalLimiter2\maximum */

}
#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

void PitchModelInitialize_initialvalues(void)
{
	/* set the initial values */
	pitch_I[0] = 0.0;		/* PID1\uD_previous_initial */
	pitch_I[1] = 0.0;		/* PID1\error_previous_initial */
	pitch_I[2] = 0.0;		/* PID1\uI_previous_initial */

}

void PitchModelInitialize_states(void)
{
	/* set the states */
	pitch_s[0] = pitch_I[0];		/* PID1\uD_previous */
	pitch_s[1] = pitch_I[1];		/* PID1\error_previous */
	pitch_s[2] = pitch_I[2];		/* PID1\uI_previous */

}

void PitchModelInitialize_variables(void)
{
	/* initialize the variable memory to zero */
	memset(pitch_V, 0, pitch_variables_size * sizeof(PitchDouble));
}

/* this method is called before calculation is possible */
void PitchModelInitialize (void)
{
	PitchModelInitialize_parameters();
	PitchModelInitialize_variables();
	PitchModelInitialize_initialvalues();
	PitchModelInitialize_states();
}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void PitchCalculateInitial (void)
{

	/* set the states again, they might have changed in the initial calculation */
	PitchModelInitialize_states ();
}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void PitchCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void PitchCalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void PitchCalculateDynamic (void)
{
	/* PID1\factor = 1 / (sampletime + PID1\tauD * PID1\beta); */
	pitch_V[3] = 1.0 / (pitch_step_size + pitch_P[2] * pitch_P[3]);

	/* corrGain\input = corr; */
	pitch_V[0] = pitch_V[8];

	/* PlusMinus2\plus1 = in; */
	pitch_V[5] = pitch_V[9];

	/* PlusMinus2\minus1 = position; */
	pitch_V[6] = pitch_V[10];

	/* corrGain\output = corrGain\K * corrGain\input; */
	pitch_V[1] = pitch_P[0] * pitch_V[0];

	/* PID1\error = PlusMinus2\plus1 - PlusMinus2\minus1; */
	pitch_R[1] = pitch_V[5] - pitch_V[6];

	/* PID1\uD = PID1\factor * (((PID1\tauD * PID1\uD_previous) * PID1\beta + (PID1\tauD * PID1\kp) * (PID1\error - PID1\error_previous)) + (sampletime * PID1\kp) * PID1\error); */
	pitch_R[0] = pitch_V[3] * (((pitch_P[2] * pitch_s[0]) * pitch_P[3] + (pitch_P[2] * pitch_P[1]) * (pitch_R[1] - pitch_s[1])) + (pitch_step_size * pitch_P[1]) * pitch_R[1]);

	/* PID1\uI = PID1\uI_previous + (sampletime * PID1\uD) / PID1\tauI; */
	pitch_R[2] = pitch_s[2] + (pitch_step_size * pitch_R[0]) / pitch_P[4];

	/* PID1\output = PID1\uI + PID1\uD; */
	pitch_V[2] = pitch_R[2] + pitch_R[0];

	/* PlusMinus1\output = corrGain\output + PID1\output; */
	pitch_V[4] = pitch_V[1] + pitch_V[2];

	/* SignalLimiter2\output = if PlusMinus1\output < SignalLimiter2\minimum... ; */
	pitch_V[7] = ((pitch_V[4] < pitch_P[5]) ? 
		/* SignalLimiter2\minimum */
		pitch_P[5]
	:
		/* if PlusMinus1\output > SignalLimiter2\maximum...  */
		((pitch_V[4] > pitch_P[6]) ? 
			/* SignalLimiter2\maximum */
			pitch_P[6]
		:
			/* PlusMinus1\output */
			pitch_V[4]
		)
	);


	/* increment the step counter */
	pitch_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void PitchCalculateOutput (void)
{
	/* out = SignalLimiter2\output; */
	pitch_V[11] = pitch_V[7];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void PitchCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void PitchModelTerminate(void)
{
}

