/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_funcs.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:48:36 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

#ifndef Pitch_FUNCS_H
#define Pitch_FUNCS_H

/* Our own include files */
#include "pitch_types.h"

/* Global constants */
extern PitchBoolean pitch__initialize;
extern PitchBoolean pitch__major;
extern PitchBoolean pitch__stop_simulation;

/* Wrapper functions around strings */
PitchDouble PitchString2Double(const char* argument);
const char* PitchDouble2String(PitchDouble argument);

/* 20-sim function prototypes */
/* 20-sim stub prototypes */
#endif

