/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_model.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:48:36 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the pitch_model.c file
*/

#ifndef Pitch_MODEL_H
#define Pitch_MODEL_H

/* Our own include files */
#include "pitch_types.h"

/* Simulation variables */
extern PitchDouble pitch_start_time;
extern PitchDouble pitch_finish_time;
extern PitchDouble pitch_step_size;
extern PitchDouble pitch_time;
extern PitchInteger pitch_steps;
extern PitchBoolean pitch_initialize;
extern PitchBoolean pitch_major;
extern PitchBoolean pitch_stop_simulation;

/* Model size constants */
#define pitch_constants_size 0
#define pitch_parameters_size 7
#define pitch_initialvalues_size 3
#define pitch_variables_size 12
#define pitch_states_size 3

/* Variable arrays */
extern PitchDouble pitch_P[];
extern PitchDouble pitch_I[];
extern PitchDouble pitch_V[];
extern PitchDouble pitch_s[];
extern PitchDouble pitch_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern PitchString pitch_parameter_names[];
extern PitchString pitch_initial_value_names[];
extern PitchString pitch_variable_names[];
extern PitchString pitch_state_names[];
extern PitchString pitch_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void PitchModelInitialize (void);
/* Initialize specific model values */
void PitchModelInitialize_parameters(void);
void PitchModelInitialize_initialvalues(void);
void PitchModelInitialize_states(void);
void PitchModelInitialize_variables(void);
void PitchModelTerminate (void);

/* Computation methods */
void PitchCalculateInitial (void);
void PitchCalculateStatic (void);
void PitchCalculateInput (void);
void PitchCalculateDynamic (void);
void PitchCalculateOutput (void);
void PitchCalculateFinal (void);


#endif

