/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_submod.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:48:36 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "pitch_model.h"
#include "pitch_integ.h"
#include "pitch_funcs.h"
#include "pitch_submod.h"

/* The submodel I/O variables */
PitchInteger pitch_number_of_inputs = 3;
PitchInteger pitch_number_of_outputs = 1;

/* the names of the submodel io variables
   uncomment this part if you need these names
PitchString pitch_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
PitchString pitch_output_names[] = {
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void PitchCopyInputsToVariables (PitchDouble *u)
{
	/* Copy the input vector to the input variables */
	pitch_V[8] = u[0];		/* corr */
	pitch_V[9] = u[1];		/* in */
	pitch_V[10] = u[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void PitchCopyVariablesToOutputs (PitchDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	pitch_V[11];		/* out */

}

/* The initialization function for submodel */
void PitchInitializeSubmodel (PitchDouble *u, PitchDouble *y, PitchDouble t)
{
	/* Initialization phase (allocating memory) */
	pitch_initialize = PitchTRUE;
	pitch_steps = 0;
	PitchModelInitialize ();
	PitchDiscreteInitialize ();

	/* Copy the inputs */
	pitch_time = t;
	PitchCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	PitchCalculateInitial ();
	PitchCalculateStatic ();
	PitchCalculateInput ();
	PitchCalculateDynamic ();
	PitchCalculateOutput ();

	/* Set the outputs */
	PitchCopyVariablesToOutputs (y);

	/* End of initialization phase */
	pitch_initialize = PitchFALSE;
}

/* The function that calculates the submodel */
void PitchCalculateSubmodel (PitchDouble *u, PitchDouble *y, PitchDouble t)
{
	/* Copy the inputs */
	pitch_time = t;
	PitchCopyInputsToVariables (u);

	/* Calculate the model */
	PitchCalculateInput ();
	PitchDiscreteStep ();
	PitchCalculateOutput ();

	/* Copy the outputs */
	PitchCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void PitchTerminateSubmodel (PitchDouble *u, PitchDouble *y, PitchDouble t)
{
	/* Copy the inputs */
	pitch_time = t;
	PitchCopyInputsToVariables (u);

	/* Calculate the final model equations */
	PitchCalculateFinal ();

	/* Set the outputs */
	PitchCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	PitchModelTerminate ();
	PitchDiscreteTerminate ();
}

