/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitch_submod.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:48:36 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the pitch_model.c file
*/

#ifndef Pitch_SUBMOD_H
#define Pitch_SUBMOD_H

/* Our own include files */
#include "pitch_model.h"

/* Submodel I/O variables */
extern PitchInteger pitch_number_of_inputs;
extern PitchInteger pitch_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern PitchString pitch_input_names[];
extern PitchString pitch_output_names[];


/* The submodel functions */
void PitchInitializeSubmodel (PitchDouble *u, PitchDouble *y, PitchDouble t);
void PitchCalculateSubmodel (PitchDouble *u, PitchDouble *y, PitchDouble t);
void PitchTerminateSubmodel (PitchDouble *u, PitchDouble *y, PitchDouble t);
void PitchCopyInputsToVariables (PitchDouble *u);
void PitchCopyVariablesToOutputs (PitchDouble *y);

#endif

