/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  pitchmodel.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 21, 2026
 *  time:  7:05:01 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the pitchmodel.c file
*/

#ifndef XX_MODEL_H
#define XX_MODEL_H

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
extern XXDouble pitch_start_time;
extern XXDouble pitch_finish_time;
extern XXDouble pitch_step_size;
extern XXDouble pitch_time;
extern XXInteger pitch_steps;
extern XXBoolean pitch_initialize;
extern XXBoolean pitch_major;
extern XXBoolean pitch_stop_simulation;

/* Model size constants */
#define pitch_constants_size 0
#define pitch_parameters_size 7
#define pitch_initialvalues_size 3
#define pitch_variables_size 12
#define pitch_states_size 3

/* Variable arrays */
extern XXDouble pitch_P[];
extern XXDouble pitch_I[];
extern XXDouble pitch_V[];
extern XXDouble pitch_s[];
extern XXDouble pitch_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern XXString pitch_parameter_names[];
extern XXString pitch_initial_value_names[];
extern XXString pitch_variable_names[];
extern XXString pitch_state_names[];
extern XXString pitch_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void XXModelInitialize (void);
/* Initialize specific model values */
void XXModelInitialize_parameters(void);
void XXModelInitialize_initialvalues(void);
void XXModelInitialize_states(void);
void XXModelInitialize_variables(void);
void XXModelTerminate (void);

/* Computation methods */
void XXCalculateInitial (void);
void XXCalculateStatic (void);
void XXCalculateInput (void);
void XXCalculateDynamic (void);
void XXCalculateOutput (void);
void XXCalculateFinal (void);


#endif

