/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 21, 2026
 *  time:  7:05:01 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "pitch_controller.h"
#include "pitch_integ.h"
#include "xxfuncs.h"
#include "pitch_submod.h"

/* The submodel I/O variables */
XXInteger pitch_number_of_inputs = 3;
XXInteger pitch_number_of_outputs = 1;

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString xx_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
XXString xx_output_names[] = {
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void pitchCopyInputsToVariables (XXDouble *u)
{
	/* Copy the input vector to the input variables */
	pitch_V[8] = u[0];		/* corr */
	pitch_V[9] = u[1];		/* in */
	pitch_V[10] = u[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void pitchCopyVariablesToOutputs (XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	pitch_V[11];		/* out */

}

/* The initialization function for submodel */
void pitchInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Initialization phase (allocating memory) */
	pitch_initialize = XXTRUE;
	pitch_steps = 0;
	pitchModelInitialize ();
	pitchDiscreteInitialize ();

	/* Copy the inputs */
	pitch_time = t;
	pitchCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	pitchCalculateInitial ();
	pitchCalculateStatic ();
	pitchCalculateInput ();
	pitchCalculateDynamic ();
	pitchCalculateOutput ();

	/* Set the outputs */
	pitchCopyVariablesToOutputs (y);

	/* End of initialization phase */
	pitch_initialize = XXFALSE;
}

/* The function that calculates the submodel */
void pitchCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	pitch_time = t;
	pitchCopyInputsToVariables (u);

	/* Calculate the model */
	pitchCalculateInput ();
	pitchDiscreteStep ();
	pitchCalculateOutput ();

	/* Copy the outputs */
	pitchCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void pitchTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	pitch_time = t;
	pitchCopyInputsToVariables (u);

	/* Calculate the final model equations */
	pitchCalculateFinal ();

	/* Set the outputs */
	pitchCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	pitchModelTerminate ();
	pitchDiscreteTerminate ();
}

