/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 21, 2026
 *  time:  7:05:01 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef PITCH_SUBMOD_H
#define PITCH_SUBMOD_H

/* Our own include files */
#include "pitch_controller.h"

/* Submodel I/O variables */
extern XXInteger pitch_number_of_inputs;
extern XXInteger pitch_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern XXString pitch_input_names[];
extern XXString pitch_output_names[];


/* The submodel functions */
void pitchInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void pitchCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void pitchTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void pitchCopyInputsToVariables (XXDouble *u);
void pitchCopyVariablesToOutputs (XXDouble *y);

#endif

