/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yawmodel.c
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 21, 2026
 *  time:  6:55:02 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   XXDouble yaw_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXString yaw_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void XXCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>
#include <string.h>

/* 20-sim include files */
#include "yaw_controller.h"
#include "xxfuncs.h"

/* the global variables */
XXDouble yaw_start_time = 0.0;
XXDouble yaw_finish_time = 20.0;
XXDouble yaw_step_size = 0.01;
XXDouble yaw_time = 0.0;
XXInteger yaw_steps = 0;
XXBoolean yaw_initialize = XXTRUE;
XXBoolean yaw_major = XXTRUE;
XXBoolean yaw_stop_simulation = XXFALSE;

/* the variable arrays */
XXDouble yaw_P[yaw_parameters_size];		/* parameters */
XXDouble yaw_I[yaw_initialvalues_size];		/* initial values */
XXDouble yaw_V[yaw_variables_size];		/* variables */
XXDouble yaw_s[yaw_states_size];		/* states */
XXDouble yaw_R[yaw_states_size];		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
XXString yaw_parameter_names[] = {
	"corrGain\\K",
	"PID1\\kp",
	"PID1\\tauD",
	"PID1\\beta",
	"PID1\\tauI",
	"SignalLimiter2\\minimum",
	"SignalLimiter2\\maximum"
,	NULL
};
XXString yaw_initial_value_names[] = {
	"PID1\\uD_previous_initial",
	"PID1\\error_previous_initial",
	"PID1\\uI_previous_initial"
,	NULL
};
XXString yaw_variable_names[] = {
	"corrGain\\corr",
	"PID1\\output",
	"",
	"PlusMinus1\\plus1",
	"SignalLimiter2\\output",
	"Splitter1\\input",
	"corr",
	"in",
	"position",
	"out"
,	NULL
};
XXString yaw_state_names[] = {
	"PID1\\uD_previous",
	"PID1\\error_previous",
	"PID1\\uI_previous"
,	NULL
};
XXString yaw_rate_names[] = {
	"",
	"PID1\\error",
	""
,	NULL
};
*/

#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
void yawModelInitialize_parameters(void)
{
	/* set the parameters */
	yaw_P[0] = 0.0;		/* corrGain\K */
	yaw_P[1] = 2.6;		/* PID1\kp */
	yaw_P[2] = 0.05;		/* PID1\tauD */
	yaw_P[3] = 0.17;		/* PID1\beta */
	yaw_P[4] = 9.0;		/* PID1\tauI */
	yaw_P[5] = -0.99;		/* SignalLimiter2\minimum */
	yaw_P[6] = 0.99;		/* SignalLimiter2\maximum */

}
#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

void yawModelInitialize_initialvalues(void)
{
	/* set the initial values */
	yaw_I[0] = 0.0;		/* PID1\uD_previous_initial */
	yaw_I[1] = 0.0;		/* PID1\error_previous_initial */
	yaw_I[2] = 0.0;		/* PID1\uI_previous_initial */

}

void yawModelInitialize_states(void)
{
	/* set the states */
	yaw_s[0] = yaw_I[0];		/* PID1\uD_previous */
	yaw_s[1] = yaw_I[1];		/* PID1\error_previous */
	yaw_s[2] = yaw_I[2];		/* PID1\uI_previous */

}

void yawModelInitialize_variables(void)
{
	/* initialize the variable memory to zero */
	memset(yaw_V, 0, yaw_variables_size * sizeof(XXDouble));
}

/* this method is called before calculation is possible */
void yawModelInitialize (void)
{
	yawModelInitialize_parameters();
	yawModelInitialize_variables();
	yawModelInitialize_initialvalues();
	yawModelInitialize_states();
}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void yawCalculateInitial (void)
{

	/* set the states again, they might have changed in the initial calculation */
	yawModelInitialize_states ();
}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void yawCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void yawCalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void yawCalculateDynamic (void)
{
	/* PID1\factor = 1 / (sampletime + PID1\tauD * PID1\beta); */
	yaw_V[2] = 1.0 / (yaw_step_size + yaw_P[2] * yaw_P[3]);

	/* PlusMinus1\plus1 = in; */
	yaw_V[3] = yaw_V[7];

	/* Splitter1\input = position; */
	yaw_V[5] = yaw_V[8];

	/* corrGain\corr = corrGain\K * Splitter1\input; */
	yaw_V[0] = yaw_P[0] * yaw_V[5];

	/* PID1\error = PlusMinus1\plus1 - Splitter1\input; */
	yaw_R[1] = yaw_V[3] - yaw_V[5];

	/* PID1\uD = PID1\factor * (((PID1\tauD * PID1\uD_previous) * PID1\beta + (PID1\tauD * PID1\kp) * (PID1\error - PID1\error_previous)) + (sampletime * PID1\kp) * PID1\error); */
	yaw_R[0] = yaw_V[2] * (((yaw_P[2] * yaw_s[0]) * yaw_P[3] + (yaw_P[2] * yaw_P[1]) * (yaw_R[1] - yaw_s[1])) + (yaw_step_size * yaw_P[1]) * yaw_R[1]);

	/* PID1\uI = PID1\uI_previous + (sampletime * PID1\uD) / PID1\tauI; */
	yaw_R[2] = yaw_s[2] + (yaw_step_size * yaw_R[0]) / yaw_P[4];

	/* PID1\output = PID1\uI + PID1\uD; */
	yaw_V[1] = yaw_R[2] + yaw_R[0];

	/* SignalLimiter2\output = if PID1\output < SignalLimiter2\minimum... ; */
	yaw_V[4] = ((yaw_V[1] < yaw_P[5]) ? 
		/* SignalLimiter2\minimum */
		yaw_P[5]
	:
		/* if PID1\output > SignalLimiter2\maximum...  */
		((yaw_V[1] > yaw_P[6]) ? 
			/* SignalLimiter2\maximum */
			yaw_P[6]
		:
			/* PID1\output */
			yaw_V[1]
		)
	);


	/* increment the step counter */
	yaw_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void yawCalculateOutput (void)
{
	/* corr = corrGain\corr; */
	yaw_V[6] = yaw_V[0];

	/* out = SignalLimiter2\output; */
	yaw_V[9] = yaw_V[4];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void yawCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void yawModelTerminate(void)
{
}

