/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 21, 2026
 *  time:  7:05:01 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "yaw_controller.h"
#include "yaw_integ.h"
#include "xxfuncs.h"
#include "yaw_submod.h"

/* The submodel I/O variables */
XXInteger yaw_number_of_inputs = 3;
XXInteger yaw_number_of_outputs = 1;

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString yaw_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
XXString yaw_output_names[] = {
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void yawCopyInputsToVariables (XXDouble *u)
{
	/* Copy the input vector to the input variables */
	yaw_V[8] = u[0];		/* corr */
	yaw_V[9] = u[1];		/* in */
	yaw_V[10] = u[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void yawCopyVariablesToOutputs (XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	yaw_V[11];		/* out */

}

/* The initialization function for submodel */
void yawInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Initialization phase (allocating memory) */
	yaw_initialize = XXTRUE;
	yaw_steps = 0;
	yawModelInitialize ();
	yawDiscreteInitialize ();

	/* Copy the inputs */
	yaw_time = t;
	yawCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	yawCalculateInitial ();
	yawCalculateStatic ();
	yawCalculateInput ();
	yawCalculateDynamic ();
	yawCalculateOutput ();

	/* Set the outputs */
	yawCopyVariablesToOutputs (y);

	/* End of initialization phase */
	yaw_initialize = XXFALSE;
}

/* The function that calculates the submodel */
void yawCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	yaw_time = t;
	yawCopyInputsToVariables (u);

	/* Calculate the model */
	yawCalculateInput ();
	yawDiscreteStep ();
	yawCalculateOutput ();

	/* Copy the outputs */
	yawCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void yawTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	yaw_time = t;
	yawCopyInputsToVariables (u);

	/* Calculate the final model equations */
	yawCalculateFinal ();

	/* Set the outputs */
	yawCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	yawModelTerminate ();
	yawDiscreteTerminate ();
}

