/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 21, 2026
 *  time:  7:05:01 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef YAW_SUBMOD_H
#define YAW_SUBMOD_H

/* Our own include files */
#include "yaw_controller.h"

/* Submodel I/O variables */
extern XXInteger yaw_number_of_inputs;
extern XXInteger yaw_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern XXString yaw_input_names[];
extern XXString yaw_output_names[];


/* The submodel functions */
void yawInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void yawCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void yawTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void yawCopyInputsToVariables (XXDouble *u);
void yawCopyVariablesToOutputs (XXDouble *y);

#endif

