/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yawmodel.h
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 21, 2026
 *  time:  6:55:02 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the yawmodel.c file
*/

#ifndef Yaw_MODEL_H
#define Yaw_MODEL_H

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
extern XXDouble yaw_start_time;
extern XXDouble yaw_finish_time;
extern XXDouble yaw_step_size;
extern XXDouble yaw_time;
extern XXInteger yaw_steps;
extern XXBoolean yaw_initialize;
extern XXBoolean yaw_major;
extern XXBoolean yaw_stop_simulation;

/* Model size constants */
#define yaw_constants_size 0
#define yaw_parameters_size 7
#define yaw_initialvalues_size 3
#define yaw_variables_size 10
#define yaw_states_size 3

/* Variable arrays */
extern XXDouble yaw_P[];
extern XXDouble yaw_I[];
extern XXDouble yaw_V[];
extern XXDouble yaw_s[];
extern XXDouble yaw_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern XXString yaw_parameter_names[];
extern XXString yaw_initial_value_names[];
extern XXString yaw_variable_names[];
extern XXString yaw_state_names[];
extern XXString yaw_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void YawModelInitialize (void);
/* Initialize specific model values */
void YawModelInitialize_parameters(void);
void YawModelInitialize_initialvalues(void);
void YawModelInitialize_states(void);
void YawModelInitialize_variables(void);
void YawModelTerminate (void);

/* Computation methods */
void YawCalculateInitial (void);
void YawCalculateStatic (void);
void YawCalculateInput (void);
void YawCalculateDynamic (void);
void YawCalculateOutput (void);
void YawCalculateFinal (void);


#endif

