/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 21, 2026
 *  time:  7:05:01 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Discrete
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these as examples.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "yaw_integ.h"
#include "yaw_controller.h"

/* global variables prototypes */
extern XXDouble yaw_time;
extern XXDouble yaw_step_size;

#define yaw_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void yawDiscreteInitialize (void)
{
	/* nothing to be done */
	yaw_major = XXTRUE;
}

/* the termination of the Discrete integration method */
void yawDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void yawDiscreteStep (void)
{
	XXInteger index;

	/* for each of the supplied states */
	for (index = 0; index < yaw_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		yaw_s [index] = yaw_R [index];
	}
	/* increment the simulation time */
	yaw_time += yaw_step_size;

	yaw_major = XXTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	yawCalculateDynamic ();
}

