/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_integ.h
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:45:41 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef Yaw_INTEG_H
#define Yaw_INTEG_H

/* 20-sim include files */
#include "yaw_types.h"

/* the chosen integration method */
#define Discrete_METHOD

/* the integration methods */
void YawDiscreteInitialize (void);
void YawDiscreteTerminate (void);
void YawDiscreteStep (void);

extern YawBoolean yaw_major;

#endif

