/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  yaw_integ.c
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  May 27, 2026
 *  time:  9:45:41 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Discrete
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these as examples.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "yaw_integ.h"
#include "yaw_model.h"

/* global variables prototypes */
extern YawDouble yaw_time;
extern YawDouble yaw_step_size;

#define yaw_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void YawDiscreteInitialize (void)
{
	/* nothing to be done */
	yaw_major = YawTRUE;
}

/* the termination of the Discrete integration method */
void YawDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void YawDiscreteStep (void)
{
	YawInteger index;

	/* for each of the supplied states */
	for (index = 0; index < yaw_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		yaw_s [index] = yaw_R [index];
	}
	/* increment the simulation time */
	yaw_time += yaw_step_size;

	yaw_major = YawTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	YawCalculateDynamic ();
}

